title:              Qauland's Sandbox
tagline:            
description:        
url:                http://qauland.github.io

author:
  name:             Qauland
  url:              https://twitter.com/qauland
  email:            ktbstsn@outlook.co.id

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           11
paginate_path:      "/hlm:num"
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js

plugins:
  - jekyll-paginate
