title:              Qauland's Sandbox
tagline:            Bukan kotak pasir yang indah
description:        Situs ini dibuat dengan tujuan untuk menguji coba. Beberapa artikel yang ada di situs ini mungkin akan muncul di blog WordPress saya.
url:                http://qauland.github.io

author:
  name:             Qauland
  url:              https://twitter.com/qauland
  email:            ktbstsn@outlook.co.id

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js

plugins:
  - jekyll-paginate
